controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["wheel1_joint", "wheel2_joint"]
    right_wheel_names: ["wheel3_joint", "wheel4_joint"]
    wheel_separation: 0.7
    wheel_radius: 0.15
    base_frame_id: "body_link"
    odom_frame_id: "odom"
    publish_rate: 50
    cmd_vel_timeout: 0.5

